# Generated by Django 3.2.8 on 2022-06-26 22:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate_creator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estimates',
            old_name='estimateId',
            new_name='file_id',
        ),
        migrations.RenameField(
            model_name='estimates',
            old_name='estimateName',
            new_name='file_name',
        ),
        migrations.AddField(
            model_name='estimates',
            name='file_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
