# Generated by Django 3.2.8 on 2022-06-26 22:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estimates',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=100)),
                ('file_date', models.DateField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
